data_dir: data
examples_filename: examples.yaml
input_type: Any
model_class_filename: model.py
model_class_name: Model
model_framework: sklearn
model_metadata:
  model_binary_dir: model
  supports_predict_proba: true
model_module_dir: model
model_name: null
model_type: Model
python_version: py39
requirements:
- scikit-learn==1.0.2
- threadpoolctl==3.0.0
- joblib==1.1.0
- numpy==1.20.3
- scipy==1.7.3
resources:
  cpu: 500m
  memory: 512m
  use_gpu: false
system_packages: []
