[workspace]
members = ["core", "python_bindings"]
resolver = "2"

[workspace.dependencies]
# Shared dependencies
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.12", features = ["blocking", "json", "stream", "http2", "default-tls", "native-tls-alpn"] }
openssl = { version = "0.10", features = ["vendored"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
once_cell = "1.21"
rand = "0.8"
