bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: Flan-T5 XL
model_type: custom
python_version: py39
requirements:
  - transformers
  - torch
  - accelerate
  - sentencepiece
    # TODO: Move the ones below to a training only requirements when ready
  - rich
  - pandas
  - numpy
resources:
  cpu: '3'
  memory: 14Gi
  use_gpu: true
secrets: {}
spec_version: '2.0'
system_packages: []
live_reload: false
train:
  resources:
    cpu: '3'
    memory: 14Gi
    use_gpu: true
  training_class_filename: train.py
  training_class_name: Train
  training_module_dir: train
  variables:
    dataset_url: https://raw.githubusercontent.com/bolasm/random-datasets/main/partial_dataset.csv
