name: Build and Push Truss Base Images (if needed)

on:
  workflow_dispatch:
    inputs:
      new_base_image_version:
        required: true
        type: string
        description: "New base image version"
      build_base_images:
        required: true
        type: string
        description: "Build base images flag"
  workflow_call:
    inputs:
      new_base_image_version:
        required: true
        type: string
      build_base_images:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-and-push-truss-base-images-if-needed:
    if: ${{ inputs.build_base_images == 'true' }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        use_gpu: ["y", "n"]
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python/
      - run: uv sync
      - shell: bash
        run: |
          uv run bin/generate_base_images.py \
            --use-gpu ${{ matrix.use_gpu }}  \
            --python-version ${{ matrix.python_version }} \
            --version-tag ${{ inputs.new_base_image_version }} \
            --skip-login --push
