name: Merge release into main

on:
  push:
    branches:
      - release

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure Git user as basetenbot
      run: |
        git config user.name "basetenbot"
        git config user.email "basetenbot@baseten.co"

    - name: Fetch all branches
      run: |
        git fetch --all

    - name: Merge release into main with priority on main changes
      run: |
        git checkout main
        git merge --strategy-option=ours release -m "Merge release into main prioritizing main changes"
        git push origin main
      env:
        GH_TOKEN: ${{ secrets.BASETENBOT_GITHUB_TOKEN }}
